# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/1082/bin/cmake

# The command to remove a file.
RM = /snap/cmake/1082/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/robin/msggenerator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/robin/msggenerator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/snap/cmake/1082/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/cmake/1082/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/robin/msggenerator/CMakeFiles /home/robin/msggenerator//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/robin/msggenerator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named msggenerator

# Build rule for target.
msggenerator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 msggenerator
.PHONY : msggenerator

# fast build rule for target.
msggenerator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msggenerator.dir/build.make CMakeFiles/msggenerator.dir/build
.PHONY : msggenerator/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msggenerator.dir/build.make CMakeFiles/msggenerator.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msggenerator.dir/build.make CMakeFiles/msggenerator.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msggenerator.dir/build.make CMakeFiles/msggenerator.dir/main.cpp.s
.PHONY : main.cpp.s

msg_outline/Cmdmsg.o: msg_outline/Cmdmsg.cpp.o
.PHONY : msg_outline/Cmdmsg.o

# target to build an object file
msg_outline/Cmdmsg.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msggenerator.dir/build.make CMakeFiles/msggenerator.dir/msg_outline/Cmdmsg.cpp.o
.PHONY : msg_outline/Cmdmsg.cpp.o

msg_outline/Cmdmsg.i: msg_outline/Cmdmsg.cpp.i
.PHONY : msg_outline/Cmdmsg.i

# target to preprocess a source file
msg_outline/Cmdmsg.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msggenerator.dir/build.make CMakeFiles/msggenerator.dir/msg_outline/Cmdmsg.cpp.i
.PHONY : msg_outline/Cmdmsg.cpp.i

msg_outline/Cmdmsg.s: msg_outline/Cmdmsg.cpp.s
.PHONY : msg_outline/Cmdmsg.s

# target to generate assembly for a file
msg_outline/Cmdmsg.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msggenerator.dir/build.make CMakeFiles/msggenerator.dir/msg_outline/Cmdmsg.cpp.s
.PHONY : msg_outline/Cmdmsg.cpp.s

msg_outline/Generalmsg.o: msg_outline/Generalmsg.cpp.o
.PHONY : msg_outline/Generalmsg.o

# target to build an object file
msg_outline/Generalmsg.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msggenerator.dir/build.make CMakeFiles/msggenerator.dir/msg_outline/Generalmsg.cpp.o
.PHONY : msg_outline/Generalmsg.cpp.o

msg_outline/Generalmsg.i: msg_outline/Generalmsg.cpp.i
.PHONY : msg_outline/Generalmsg.i

# target to preprocess a source file
msg_outline/Generalmsg.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msggenerator.dir/build.make CMakeFiles/msggenerator.dir/msg_outline/Generalmsg.cpp.i
.PHONY : msg_outline/Generalmsg.cpp.i

msg_outline/Generalmsg.s: msg_outline/Generalmsg.cpp.s
.PHONY : msg_outline/Generalmsg.s

# target to generate assembly for a file
msg_outline/Generalmsg.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msggenerator.dir/build.make CMakeFiles/msggenerator.dir/msg_outline/Generalmsg.cpp.s
.PHONY : msg_outline/Generalmsg.cpp.s

msg_outline/Logmsg.o: msg_outline/Logmsg.cpp.o
.PHONY : msg_outline/Logmsg.o

# target to build an object file
msg_outline/Logmsg.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msggenerator.dir/build.make CMakeFiles/msggenerator.dir/msg_outline/Logmsg.cpp.o
.PHONY : msg_outline/Logmsg.cpp.o

msg_outline/Logmsg.i: msg_outline/Logmsg.cpp.i
.PHONY : msg_outline/Logmsg.i

# target to preprocess a source file
msg_outline/Logmsg.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msggenerator.dir/build.make CMakeFiles/msggenerator.dir/msg_outline/Logmsg.cpp.i
.PHONY : msg_outline/Logmsg.cpp.i

msg_outline/Logmsg.s: msg_outline/Logmsg.cpp.s
.PHONY : msg_outline/Logmsg.s

# target to generate assembly for a file
msg_outline/Logmsg.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msggenerator.dir/build.make CMakeFiles/msggenerator.dir/msg_outline/Logmsg.cpp.s
.PHONY : msg_outline/Logmsg.cpp.s

msg_outline/MsgHistory.o: msg_outline/MsgHistory.cpp.o
.PHONY : msg_outline/MsgHistory.o

# target to build an object file
msg_outline/MsgHistory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msggenerator.dir/build.make CMakeFiles/msggenerator.dir/msg_outline/MsgHistory.cpp.o
.PHONY : msg_outline/MsgHistory.cpp.o

msg_outline/MsgHistory.i: msg_outline/MsgHistory.cpp.i
.PHONY : msg_outline/MsgHistory.i

# target to preprocess a source file
msg_outline/MsgHistory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msggenerator.dir/build.make CMakeFiles/msggenerator.dir/msg_outline/MsgHistory.cpp.i
.PHONY : msg_outline/MsgHistory.cpp.i

msg_outline/MsgHistory.s: msg_outline/MsgHistory.cpp.s
.PHONY : msg_outline/MsgHistory.s

# target to generate assembly for a file
msg_outline/MsgHistory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msggenerator.dir/build.make CMakeFiles/msggenerator.dir/msg_outline/MsgHistory.cpp.s
.PHONY : msg_outline/MsgHistory.cpp.s

msg_outline/T2msg.o: msg_outline/T2msg.cpp.o
.PHONY : msg_outline/T2msg.o

# target to build an object file
msg_outline/T2msg.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msggenerator.dir/build.make CMakeFiles/msggenerator.dir/msg_outline/T2msg.cpp.o
.PHONY : msg_outline/T2msg.cpp.o

msg_outline/T2msg.i: msg_outline/T2msg.cpp.i
.PHONY : msg_outline/T2msg.i

# target to preprocess a source file
msg_outline/T2msg.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msggenerator.dir/build.make CMakeFiles/msggenerator.dir/msg_outline/T2msg.cpp.i
.PHONY : msg_outline/T2msg.cpp.i

msg_outline/T2msg.s: msg_outline/T2msg.cpp.s
.PHONY : msg_outline/T2msg.s

# target to generate assembly for a file
msg_outline/T2msg.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msggenerator.dir/build.make CMakeFiles/msggenerator.dir/msg_outline/T2msg.cpp.s
.PHONY : msg_outline/T2msg.cpp.s

msg_outline/T3msg.o: msg_outline/T3msg.cpp.o
.PHONY : msg_outline/T3msg.o

# target to build an object file
msg_outline/T3msg.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msggenerator.dir/build.make CMakeFiles/msggenerator.dir/msg_outline/T3msg.cpp.o
.PHONY : msg_outline/T3msg.cpp.o

msg_outline/T3msg.i: msg_outline/T3msg.cpp.i
.PHONY : msg_outline/T3msg.i

# target to preprocess a source file
msg_outline/T3msg.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msggenerator.dir/build.make CMakeFiles/msggenerator.dir/msg_outline/T3msg.cpp.i
.PHONY : msg_outline/T3msg.cpp.i

msg_outline/T3msg.s: msg_outline/T3msg.cpp.s
.PHONY : msg_outline/T3msg.s

# target to generate assembly for a file
msg_outline/T3msg.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/msggenerator.dir/build.make CMakeFiles/msggenerator.dir/msg_outline/T3msg.cpp.s
.PHONY : msg_outline/T3msg.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... msggenerator"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... msg_outline/Cmdmsg.o"
	@echo "... msg_outline/Cmdmsg.i"
	@echo "... msg_outline/Cmdmsg.s"
	@echo "... msg_outline/Generalmsg.o"
	@echo "... msg_outline/Generalmsg.i"
	@echo "... msg_outline/Generalmsg.s"
	@echo "... msg_outline/Logmsg.o"
	@echo "... msg_outline/Logmsg.i"
	@echo "... msg_outline/Logmsg.s"
	@echo "... msg_outline/MsgHistory.o"
	@echo "... msg_outline/MsgHistory.i"
	@echo "... msg_outline/MsgHistory.s"
	@echo "... msg_outline/T2msg.o"
	@echo "... msg_outline/T2msg.i"
	@echo "... msg_outline/T2msg.s"
	@echo "... msg_outline/T3msg.o"
	@echo "... msg_outline/T3msg.i"
	@echo "... msg_outline/T3msg.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

